backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BlogController@index');
Route::get('/post/{id}', 'BlogController@post');
Route::post('/post/{id}', 'BlogController@comentario');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/settings', 'SettingsController@index')->name('settings');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function() {
    Route::resource('artigos', 'ArtigoController');
    Route::resource('categorias', 'CategoriaController');
    Route::resource('comentarios', 'ComentarioController');
    Route::resource('tags', 'TagController');
});

backend/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ config('app.name') }} - Painel de Usuário</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">TI</span>

                <b>{{ config('app.name') }}</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">Olá, {!! Auth::user()->name !!}</span> <i class="fa fa-chevron-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="{{url('/')}}">Visualizar Blog</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Perfil</a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation">
                                    <a href="{!! url('/logout') !!}"
                                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        <i class="fa fa-power-off"></i> <b>Sair</b>
                                    </a>
                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')

<script>
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()
        })
</script>
</body>
</html>

backend/resources/views/layouts/blog.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <title>{{ config('app.name') }}</title>
     <!-- DEFAULT META TAGS -->
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <!-- FONTS -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Lora:400italic,700italic" rel="stylesheet" type="text/css">
    
    <!-- CSS -->
    <link rel="stylesheet" id="default-style-css"  href="/files/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" id="fontawesome-style-css" href="/files/css/font-awesome.min.css" type="text/css" media="all" />
    <link rel="stylesheet" id="ionic-icons-style-css" href="/files/css/ionicons.css" type="text/css" media="all" />
	<link rel="stylesheet" id="isotope-style-css"  href="/files/css/isotope.css" type="text/css" media="all" />
    <link rel="stylesheet" id="mqueries-style-css"  href="/files/css/mqueries.css" type="text/css" media="all" />
    
    <!-- FAVICON -->
    <link rel="shortcut icon" href="/files/uploads/favicon.png"/>

</head>
<body>
<!-- PAGE CONTENT -->
<div id="page-content">

	<!-- HEADER -->
	<header id="header" class="header-bordered header-transparent transparent-light">        
		<div class="header-inner clearfix">
			
            <!-- LOGO -->
            <div id="logo" class="left-float">
                <a href="{{ url('/')}}">
                	<img id="scroll-logo" src="/files/uploads/logo-sudo-scroll.png" srcset="/files/uploads/logo-sudo-scroll.png 1x, files/uploads/logo-sudo-scroll@2x.png 2x" alt="Logo Scroll">
                	<img id="dark-logo" src="/files/uploads/logo-sudo-dark.png" srcset="/files/uploads/logo-sudo-dark.png 1x, files/uploads/logo-sudo-dark@2x.png 2x" alt="Logo Dark">
                	<img id="light-logo" src="/files/uploads/logo-sudo-light.png" srcset="/files/uploads/logo-sudo-light.png 1x, files/uploads/logo-sudo-light@2x.png 2x" alt="Logo Light">
                </a>
            </div>
            
            <!-- MAIN NAVIGATION -->
            <div id="menu" class="right-float">
    			<a href="#" class="responsive-nav-toggle"><span class="hamburger"></span></a>
                <div class="menu-inner">
                    <nav id="main-nav">
                        <ul>
                            @if (Route::has('login'))
                                    @auth
                                    <li class="menu-item-has-children">
                                        <a href="{{ url('/home') }}">Painel</a>
                                    </li>
                                    @else
                                    <li class="menu-item-has-children">
                                        <a href="{{ route('login') }}">Login</a>
                                    </li>
                                    <li class="menu-item-has-children">
                                        <a href="{{ route('register') }}">Register</a>
                                    </li>
                                    @endauth
                            @endif                            
                        </ul>
                    </nav>
                    
                    <div id="menu-misc" class="clearfix">    
                        
                        <!-- HEADER SEARCH -->
                        <div id="header-search">
                            <a href="#" id="show-search"><i class="fa fa-search"></i></a>
                            <div class="header-search-content">
                                <form action="http://www.spab-rice.com/themeforest/sudo/demo/search.html" method="get">
                                    <a href="#" id="close-search"></a>
                                    <input type="text" name="q" class="form-control" value="" placeholder="Enter your search ...">
                                    <h5 class="subtitle-1">... & press enter to start</h5>
                                </form>
                                <div class="search-outer"></div>
                            </div>
                        </div>
                        
                    </div><!-- END #menu-misc -->
                </div><!-- END .menu-inner -->
            </div><!-- END #menu -->
            
		</div> <!-- END .header-inner -->
	</header>

    @yield('content')
       
    <!-- FOOTER -->  
    <footer id="footer" class="footer-dark text-light">
       	<div class="footer-inner wrapper">
       
            <div class="column-section clearfix">
            	<div class="column two-fifth">
                	<div class="widget">
                    	<img src="/files/uploads/logo-sudo-light.png" srcset="/files/uploads/logo-sudo-light.png 1x, files/uploads/logo-sudo-light@2x.png 2x" alt="Logo">
                        <div class="spacer-mini"></div>
                        <p>Este desafio tem a finalidade de qualificar você que quer ser um integrante do time de desenvolvimento da AGV, como um Desenvolvedor WEB PHP FULL-STACK.</p>
                    </div>
                    
                     <div class="widget">
                        <ul class="socialmedia-widget hover-fade-1">
                            <li class="facebook"><a href="#"></a></li>
                            <li class="twitter"><a href="#"></a></li>
                            <li class="dribbble"><a href="#"></a></li>
                            <li class="behance"><a href="#"></a></li>
                            <li class="instagram"><a href="#"></a></li>
                        </ul>
                    </div>
                    
                </div>
            	<div class="column one-fifth">
                	<div class="widget">
                    	<h6 class="widget-title uppercase">Quick Menu</h6>
                        <ul class="menu">
                        	<li><a href="#">About Us</a></li>
                        	<li><a href="#">Portfolio</a></li>
                        	<li><a href="#">Our Team</a></li>
                        	<li><a href="#">Support</a></li>
                        	<li><a href="#">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
            	<div class="column one-fifth">
                	<div class="widget">
                    	<h6 class="widget-title uppercase">Categories</h6>
                        <ul class="menu">
                        	<li><a href="#">Design</a></li>
                        	<li><a href="#">Graphic</a></li>
                        	<li><a href="#">Stories</a></li>
                        	<li><a href="#">Photography</a></li>
                        	<li><a href="#">Video</a></li>
                        </ul>
                    </div>
                </div>
            	<div class="column one-fifth last-col">
                	<div class="widget widget_recent_entries">	
                        <h6 class="widget-title uppercase">Recent Posts</h6>
                        <ul>
                            <li><a href="#">Waterfalls of Iceland</a><span class="post-date">5 hours ago</span></li>
                            <li><a href="#">Minimal Interior Elements</a><span class="post-date">11 hours ago</span></li>
                            <li><a href="#">Birds flying around</a><span class="post-date">1 day ago</span></li>
                        </ul>
                    </div>
                </div>
            </div>
                                    
            <a id="backtotop" href="#">Back to top</a>
        </div>
        
         <div class="copyright"><small>Copyright &copy; 2018 by João Cruz - Todo direito reservado.</small></div>
    </footer>
    <!-- FOOTER -->
    
</div> <!-- END #page-content -->
<!-- PAGE CONTENT -->

<!-- SCRIPTS -->
<script src="/files/js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="/files/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/files/js/jquery.visible.min.js"></script>
<script type="text/javascript" src="/files/js/tweenMax.js"></script>
<script type="text/javascript" src="/files/js/jquery.backgroundparallax.min.js"></script>
<script type="text/javascript" src="/files/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="/files/js/jquery.imagesloaded.min.js"></script>
<script type="text/javascript" src="/files/js/script.js"></script>
<!-- SCRIPTS -->
</body>
</html>

backend/resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

backend/resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

backend/resources/views/layouts/menu.blade.php
<li class="{{ Request::is('/home*') ? 'active' : '' }}">
    <a href="{!! url('/home') !!}"><i class="fa fa-home"></i><span>Painel</span></a>
</li>
<li class="{{ Request::is('artigos*') ? 'active' : '' }}">
    <a href="{!! route('artigos.index') !!}"><i class="fa fa-file"></i><span>Meus Artigos</span></a>
</li>

<li class="{{ Request::is('categorias*') ? 'active' : '' }}">
    <a href="{!! route('categorias.index') !!}"><i class="fa fa-folder"></i><span>Categorias</span></a>
</li>

<li class="{{ Request::is('comentarios*') ? 'active' : '' }}">
    <a href="{!! route('comentarios.index') !!}"><i class="fa fa-comment"></i><span>Comentários</span></a>
</li>

<li class="{{ Request::is('tags*') ? 'active' : '' }}">
    <a href="{!! route('tags.index') !!}"><i class="fa fa-tags"></i><span>Tags</span></a>
</li>

<li class="{{ Request::is('tags*') ? 'active' : '' }}">
    <a href="{{ route('settings') }}"><i class="fa fa-settings"></i><span>Configurações</span></a>
</li>

backend/resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>